apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"environment":"dev"},"name":"mqttbridge","namespace":"dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mqttbridge"}},"template":{"metadata":{"labels":{"app":"mqttbridge"}},"spec":{"containers":[{"env":[{"name":"INFLUXDB_ADDRESS","value":"influxdb"},{"name":"MOSQUITTO_ADDRESS","value":"mosquitto"}],"image":"gluteusmaximus/mqttbridge","name":"mqttbridge","resources":{"limits":{"cpu":"250m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"nodeSelector":{"beta.kubernetes.io/os":"linux"}}}}}
  creationTimestamp: "2020-07-29T06:13:33Z"
  generation: 1
  labels:
    environment: dev
  name: mqttbridge
  namespace: dev
  resourceVersion: "2408173"
  selfLink: /apis/apps/v1/namespaces/dev/deployments/mqttbridge
  uid: 39ecc723-2777-4f88-8c26-9767dd8516d1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mqttbridge
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mqttbridge
    spec:
      containers:
      - env:
        - name: INFLUXDB_ADDRESS
          value: influxdb
        - name: MOSQUITTO_ADDRESS
          value: mosquitto
        image: gluteusmaximus/mqttbridge
        imagePullPolicy: Always
        name: mqttbridge
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-07-29T06:13:33Z"
    lastUpdateTime: "2020-07-29T06:13:33Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-07-29T06:13:33Z"
    lastUpdateTime: "2020-07-29T06:13:33Z"
    message: ReplicaSet "mqttbridge-59b55d9b69" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
