apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-06-19T16:15:36Z"
  generateName: mosquitto-8b4b5ffcc-
  labels:
    app: mosquitto
    pod-template-hash: 8b4b5ffcc
  name: mosquitto-8b4b5ffcc-445kv
  namespace: dev
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mosquitto-8b4b5ffcc
    uid: 39d26c91-ad6e-4c0c-8f84-ffcdd4010687
  resourceVersion: "107740940"
  selfLink: /api/v1/namespaces/dev/pods/mosquitto-8b4b5ffcc-445kv
  uid: 66c1b20a-0a59-4f02-869f-8705209711fa
spec:
  containers:
  - image: eclipse-mosquitto:1.6
    imagePullPolicy: IfNotPresent
    name: mosquitto
    ports:
    - containerPort: 1883
      name: mosquitto
      protocol: TCP
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-q4gmh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool-30543642-vmss000000
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-q4gmh
    secret:
      defaultMode: 420
      secretName: default-token-q4gmh
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-06-19T16:15:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-06-19T16:15:38Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-06-19T16:15:38Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-06-19T16:15:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://28b55a539b1cb77be8636d55ac15689aae91d21845c8e6b2db266749d50ff0da
    image: eclipse-mosquitto:1.6
    imageID: docker-pullable://eclipse-mosquitto@sha256:6ba79811d4787e10396fc5ac4784dccce235973c4351ffcd4d22f1c6ca7c44d1
    lastState: {}
    name: mosquitto
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-06-19T16:15:38Z"
  hostIP: 10.240.0.4
  phase: Running
  podIP: 10.244.0.219
  podIPs:
  - ip: 10.244.0.219
  qosClass: Burstable
  startTime: "2021-06-19T16:15:36Z"
