apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-04-20T13:29:19Z"
  generateName: mqttbridge-59b55d9b69-
  labels:
    app: mqttbridge
    pod-template-hash: 59b55d9b69
  name: mqttbridge-59b55d9b69-4dgfl
  namespace: dev
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mqttbridge-59b55d9b69
    uid: ba940e8a-2a63-4759-be36-f598ec3a06ae
  resourceVersion: "101389975"
  selfLink: /api/v1/namespaces/dev/pods/mqttbridge-59b55d9b69-4dgfl
  uid: 4d8f6355-a19d-463a-874d-f778b8d7f2d4
spec:
  containers:
  - env:
    - name: INFLUXDB_ADDRESS
      value: influxdb
    - name: MOSQUITTO_ADDRESS
      value: mosquitto
    image: gluteusmaximus/mqttbridge
    imagePullPolicy: Always
    name: mqttbridge
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-q4gmh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool-30543642-vmss000000
  nodeSelector:
    beta.kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-q4gmh
    secret:
      defaultMode: 420
      secretName: default-token-q4gmh
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-04-20T13:29:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-04-20T13:29:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-04-20T13:29:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-04-20T13:29:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://716f932509d9cfc4a5d29b7ccada40d8a8be2b75f2e983f831cd7b16f40b7df3
    image: gluteusmaximus/mqttbridge:latest
    imageID: docker-pullable://gluteusmaximus/mqttbridge@sha256:7490c7a606abbe9c803adcd430bca6763973a34254231bffc9e37ada743eae5a
    lastState: {}
    name: mqttbridge
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-04-20T13:29:30Z"
  hostIP: 10.240.0.4
  phase: Running
  podIP: 10.244.0.123
  podIPs:
  - ip: 10.244.0.123
  qosClass: Burstable
  startTime: "2021-04-20T13:29:19Z"
