apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-06-19T13:06:30Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2021-06-19T15:45:35Z"
  generateName: mqttmonitor-7f75ff6774-
  labels:
    app.kubernetes.io/instance: mqttmonitor
    app.kubernetes.io/name: mqttmonitor
    pod-template-hash: 7f75ff6774
  name: mqttmonitor-7f75ff6774-xpbr8
  namespace: dev
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mqttmonitor-7f75ff6774
    uid: 8caa9f67-8193-452c-9942-62d25fcf4634
  resourceVersion: "107738637"
  selfLink: /api/v1/namespaces/dev/pods/mqttmonitor-7f75ff6774-xpbr8
  uid: c558aceb-bbaf-487d-b688-fab8c3f75581
spec:
  containers:
  - image: grafana/grafana:5.4.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: grafana
    ports:
    - containerPort: 3000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: mqttmonitor-token-cl7bm
      readOnly: true
  - env:
    - name: INFLUXDB_USER
      value: root
    - name: INFLUXDB_USER_PASSWORD
      value: root
    - name: INFLUXDB_DB
      value: home_db
    image: influxdb:1.7
    imagePullPolicy: IfNotPresent
    name: influxdb
    ports:
    - containerPort: 8086
      name: http
      protocol: TCP
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: mqttmonitor-token-cl7bm
      readOnly: true
  - image: eclipse-mosquitto:1.6
    imagePullPolicy: IfNotPresent
    name: mosquitto
    ports:
    - containerPort: 1883
      name: http
      protocol: TCP
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: mqttmonitor-token-cl7bm
      readOnly: true
  - env:
    - name: INFLUXDB_ADDRESS
      value: localhost
    - name: MOSQUITTO_ADDRESS
      value: localhost
    image: gluteusmaximus/mqttbridge:latest
    imagePullPolicy: Always
    name: mqttbridge
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: mqttmonitor-token-cl7bm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool-30543642-vmss000000
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: mqttmonitor
  serviceAccountName: mqttmonitor
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: mqttmonitor-token-cl7bm
    secret:
      defaultMode: 420
      secretName: mqttmonitor-token-cl7bm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-06-19T13:06:30Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-06-19T13:06:52Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-06-19T13:06:52Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-06-19T13:06:30Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://8de4b9862a0f454aafa01618e06572d6fc1f5c4848f66ef7209d108678c95de9
    image: grafana/grafana:5.4.3
    imageID: docker-pullable://grafana/grafana@sha256:61b7885bde628cba502dcf6f131cba052a959024d50d81d4a218950fcfa20a00
    lastState: {}
    name: grafana
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-06-19T13:06:31Z"
  - containerID: docker://4a3b012f9550abaf305a78ac08f340de8bea4fcf8fa132b7072efad00cf99a55
    image: influxdb:1.7
    imageID: docker-pullable://influxdb@sha256:719906adf2d0f83961de6c32858265044873b6644379b1c54b6903f558bf8b0e
    lastState: {}
    name: influxdb
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-06-19T13:06:32Z"
  - containerID: docker://4fd6c144703845f0a3e0030a261842416e6933b65e75286b8a40e38ef678f299
    image: eclipse-mosquitto:1.6
    imageID: docker-pullable://eclipse-mosquitto@sha256:6ba79811d4787e10396fc5ac4784dccce235973c4351ffcd4d22f1c6ca7c44d1
    lastState: {}
    name: mosquitto
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-06-19T13:06:32Z"
  - containerID: docker://fa0653e83f8e38086d74ec4de8445b903ddbc5e3d2f3737e7ab62f3391bf83cf
    image: gluteusmaximus/mqttbridge:latest
    imageID: docker-pullable://gluteusmaximus/mqttbridge@sha256:4d872b7e7d0a97ca9e355e168da32d04c2e575b3e35d972b6d5f80cb2313c2d1
    lastState:
      terminated:
        containerID: docker://bc57fb08cab3aa43bad20e476f828e972b5b4a770afe322c3ebf3ac09e7d7163
        exitCode: 1
        finishedAt: "2021-06-19T13:06:37Z"
        reason: Error
        startedAt: "2021-06-19T13:06:36Z"
    name: mqttbridge
    ready: true
    restartCount: 2
    started: true
    state:
      running:
        startedAt: "2021-06-19T13:06:52Z"
  hostIP: 10.240.0.4
  phase: Running
  podIP: 10.244.0.216
  podIPs:
  - ip: 10.244.0.216
  qosClass: BestEffort
  startTime: "2021-06-19T13:06:30Z"
