apiVersion: v1
kind: Service
metadata:
    name: "kub-9985"
    labels:
        app: "kub-9985"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kub-9985"