apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqttmonitor.fullname" . }}
  labels:
    {{- include "mqttmonitor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalport }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: grafana
#    {{- include "mqttmonitor.selectorLabels" . | nindent 4 }}
