apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "MQQTMonitor.fullname" . }}
  labels:
    {{- include "MQQTMonitor.labels" . | nindent 4 }}
spec:
  containers:
    - env:
        - name: FARMOS_DEV
          value: 'false'
        - name: KUBERNETES_PORT_443_TCP_ADDR
          value: kub-55f830eb.hcp.uksouth.azmk8s.io
        - name: KUBERNETES_PORT
          value: 'tcp://kub-55f830eb.hcp.uksouth.azmk8s.io:443'
        - name: KUBERNETES_PORT_443_TCP
          value: 'tcp://kub-55f830eb.hcp.uksouth.azmk8s.io:443'
        - name: KUBERNETES_SERVICE_HOST
          value: kub-55f830eb.hcp.uksouth.azmk8s.io
      image: farmos/farmos
      imagePullPolicy: Always
      name: bongo
      resources: {}
      securityContext:
        privileged: false
        procMount: Default
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/www/html
          name: farmdiskweb
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-l79fg
          readOnly: true
    - env:
        - name: MYSQL_ROOT_PASSWORD
          value: farmos
        - name: MYSQL_DATABASE
          value: farmos
        - name: MYSQL_USER
          value: farmos
        - name: MYSQL_PASSWORD
          value: farmos
        - name: KUBERNETES_PORT_443_TCP_ADDR
          value: kub-55f830eb.hcp.uksouth.azmk8s.io
        - name: KUBERNETES_PORT
          value: 'tcp://kub-55f830eb.hcp.uksouth.azmk8s.io:443'
        - name: KUBERNETES_PORT_443_TCP
          value: 'tcp://kub-55f830eb.hcp.uksouth.azmk8s.io:443'
        - name: KUBERNETES_SERVICE_HOST
          value: kub-55f830eb.hcp.uksouth.azmk8s.io
      image: 'mariadb:latest'
      imagePullPolicy: Always
      name: bongodb
      ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
      resources: {}
      securityContext:
        privileged: false
        procMount: Default
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: farmdisk
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-l79fg
          readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: aks-agentpool-86275814-0
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - azureDisk:
        cachingMode: ReadWrite
        diskName: farmDisk
        diskURI: >-
          /subscriptions/73a97781-98ea-4939-aa9d-f4c6233b011e/resourceGroups/MC_Kub_ResourceGroup_kub_uksouth/providers/Microsoft.Compute/disks/farmDisk
        fsType: ext4
        kind: Managed
        readOnly: false
      name: farmdisk
    - azureDisk:
        cachingMode: ReadWrite
        diskName: farmDiskWeb
        diskURI: >-
          /subscriptions/73a97781-98ea-4939-aa9d-f4c6233b011e/resourceGroups/MC_Kub_ResourceGroup_kub_uksouth/providers/Microsoft.Compute/disks/farmDiskWeb
        fsType: ext4
        kind: Managed
        readOnly: false
      name: farmdiskweb
    - name: default-token-l79fg
      secret:
        defaultMode: 420
        secretName: default-token-l79fg
